### ISSUE TITLE
Feature request download whole file

### ISSUE THREAD

**Issue by ZGainsforth** [keefo/GistPal-for-Mac#1]
Hi,

Many gists are text snippets that I can just cut and paste into my code and all is well.  However, I also have some gists which are jupyter notebooks.  In this case, I usually need to download the entire file.  Right now I have to right-click the gist, go to github, open in browser, then click the download zip button to get the whole file.

It seems it would be easy to add another menu item: "Download Gist" and it would put it in a file that I could either choose or it would go to the default downloads directory.  I've uploaded a "screenshot" showing how it may work.

Thanks,

Zack

<img width="1070" alt="Gistpal" src="https://user-images.githubusercontent.com/6864619/57888223-5abc8b00-77e6-11e9-9302-33deda7ac9c2.png">

**Comment by keefo** [comment]
Thanks. 
We will add this feature into the next release.

**Comment by keefo** [comment]
@ZGainsforth the new version 2.8.1 has been released in Mac App Store.

**Comment by ZGainsforth** [comment]
It works!  Thank you.

Zack
