### ISSUE TITLE
Search fails when there are many gists

### ISSUE THREAD

**Issue by dotherightthing** [keefo/GistPal-for-Mac#10]
When I first installed GistPal, the search always worked reliably.

However since adding a lot more gists (for a total of 205 gists), the search results don't seem to match my search terms any more.

As a result I have to use another Gist client for my searches.

MacOS: 10.14.2 (Mojave, updated today)
GistPal: 2.8.1(361)

**Comment by keefo** [comment]
Thank for submitting this issue. 
Our development team aware of this issue and we are working on v2.9 currently, which will bring a full-text indexing engine in.

**Comment by keefo** [comment]
We have released v2.9 which is available on the Mac app store Jul 7, 2021.
