### ISSUE TITLE
Editor Colors: Black on DrakGray is not readable in macOS DarkMode

### ISSUE THREAD

**Issue by Schneppi** [keefo/GistPal-for-Mac#11]
Version 2.8.1(361)
<img width="806" alt="Bildschirmfoto 2019-08-24 um 15 56 46" src="https://user-images.githubusercontent.com/46476806/63638417-cb95fd80-c687-11e9-8ae5-84052e6dcaff.png">

**Comment by Schneppi** [comment]
This happened on first start. A restart fixed the issue.

**Comment by keefo** [comment]
thx for the report. We will resolve this in the next release.

**Comment by keefo** [comment]
We have added the theme support in v2.9 which is available on the Mac app store Jul 7, 2021.
