### ISSUE TITLE
only sync the title but no code

### ISSUE THREAD

**Issue by jason-shen** [keefo/GistPal-for-Mac#12]
just brought this, it only sync the title of the gist no code at all

![Screen Shot 2020-07-12 at 15 14 49](https://user-images.githubusercontent.com/1794291/87241122-7fe07400-c452-11ea-98e5-18c3e2f99ccd.png)

**Comment by keefo** [comment]
We have released v2.9 which is available on the Mac app store Jul 7, 2021.
