### ISSUE TITLE
kill all modals as alerting mechanism

### ISSUE THREAD

**Issue by josgraha** [keefo/GistPal-for-Mac#13]
as a user I don't need to see modals as alerts as they obstruct other useful information and steal focus.  this is counterproductive, please remove the use of modals as an alerting mechanism

**Comment by keefo** [comment]
Thank you @josgraha , That is a reasonable request. We will push a release ASAP.

**Comment by keefo** [comment]
2.9.1 is released. You should see the upgrade in the next couple of days.
