### ISSUE TITLE
Authentification error 

### ISSUE THREAD

**Issue by 6ui11em** [keefo/GistPal-for-Mac#14]
I'm using GistPal 1.8.1 with MacOS Catalina and I'm getting the following error:

![Captura de pantalla 2021-09-01 a las 0 07 25](https://user-images.githubusercontent.com/131965/131582150-c07ec40e-e61e-4399-9c03-64303455064b.png)

I tried to logout and login several times but always get this error.

**Comment by Dezinger** [comment]
The same problem
![2021-09-06 15-43-29](https://user-images.githubusercontent.com/432272/132219487-85f81864-69e4-463d-b2af-a48dd3e2da78.png)

**Comment by keefo** [comment]
Hi Aleksey

the token format which 2.8 uses is no longer supported by GitHub. Nothing the gistpal 2.8 can do in this case. 

The only option is to upgrade to a newer version of gistpal which is a free upgrade and it does not support some older version of macOS.

**Comment by 6ui11em** [comment]
It's a shame GistPal drop support for older versions of MacOS. Catalina is not so old OS version.
