### ISSUE TITLE
Typo in menu

### ISSUE THREAD

**Issue by dotherightthing** [keefo/GistPal-for-Mac#5]
A *Sort by ...* menu displays below the search field.

The third option is *Sort by tilte*.

This should read *Sort by title*.

GistPal Version: 2.8.1(361)

**Comment by keefo** [comment]
Thanks for your input.
We will fix this in the very next release.

**Comment by keefo** [comment]
We have fixed this issue in the v2.9 which is available on the Mac app store Jul 7, 2021.
