### ISSUE TITLE
'Is markdown' checkbox won't stay checked

### ISSUE THREAD

**Issue by dotherightthing** [keefo/GistPal-for-Mac#7]
1. Create new gist
2. Filename: gistfile1.md
3. Check 'is Markdown' -  checkbox immediately un-checks itself
4. Add some markdown: `# heading 1`
5. Check 'is Markdown' -  checkbox immediately un-checks itself

GistPal Version: 2.8.1(361)

**Comment by keefo** [comment]
Added into our fix list.

**Comment by keefo** [comment]
We have fixed this issue in the v2.9 which is available on the Mac app store Jul 7, 2021.
