### ISSUE TITLE
Add support/styling for quotes

### ISSUE THREAD

**Issue by dotherightthing** [keefo/GistPal-for-Mac#9]
Currently quotes display the same way as regular text blocks.

The *Headers & Quotes* section of Github's [Mastering Markdown](https://guides.github.com/features/mastering-markdown/) guide shows the styling applied on Github (and in gists).

**Comment by keefo** [comment]
Added into our plan list.

**Comment by keefo** [comment]
We have added this support in v2.9 which is available on the Mac app store Jul 7, 2021.

<img width="567" alt="Screen Shot 2021-07-08 at 8 38 16 PM" src="https://user-images.githubusercontent.com/809588/125019773-6efa1c80-e02c-11eb-9dba-3dc14410a353.png">
